
name: CI pipeline #comando para dar el nombre del flujo

#indica cuando se ejecuta el flujo:
on:
  pull_request:
  push:
    branches:
      - develop

#acciones que se ejecutaran en el servidor:
jobs:
  frontend-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository (git clone)
        uses: actions/checkout@v4

      - name: Setup node (instalar node)
        uses: actions/setup-node@v4
        with: 
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Contruir frontend 
        run: npm run build